<?php
/**
 * modules/principal/payroll-approval/index.php
 * Principal Portal – Payroll Approvals
 */
require_once __DIR__ . '/../../../config/config.php';
require_once __DIR__ . '/../../../includes/auth.php';
requirePrincipal();

// ── Pending periods (PROCESSING — awaiting Principal approval) ────────────────
$pending = $pdo->query("
    SELECT pp.*,
           COUNT(pr.payroll_id)      AS emp_count,
           SUM(pr.gross_pay)         AS total_gross,
           SUM(pr.total_deductions)  AS total_deductions,
           SUM(pr.net_pay)           AS total_net
    FROM payroll_periods pp
    LEFT JOIN payroll_records pr ON pp.period_id = pr.period_id
    WHERE pp.status = 'PROCESSING'
    GROUP BY pp.period_id
    ORDER BY pp.pay_period_start DESC
")->fetchAll();

// ── History (APPROVED / RELEASED) ────────────────────────────────────────────
$history = $pdo->query("
    SELECT pp.*,
           COUNT(pr.payroll_id) AS emp_count,
           SUM(pr.net_pay)      AS total_net
    FROM payroll_periods pp
    LEFT JOIN payroll_records pr ON pp.period_id = pr.period_id
    WHERE pp.status IN ('APPROVED','RELEASED')
    GROUP BY pp.period_id
    ORDER BY pp.pay_period_start DESC
")->fetchAll();

$pageTitle = 'Payroll Approvals — Principal Portal';
$extraCSS  = [BASE_URL . 'assets/css/principal.css'];
require_once __DIR__ . '/../../../includes/head.php';
?>
<body>
<div class="layout">
<?php include __DIR__ . '/../../../includes/principal-sidebar.php'; ?>

<div class="main">

  <!-- ── Page Header ── -->
  <div class="header">
    <div style="display:flex;align-items:center;gap:10px;">
      <i class="fa fa-file-invoice-dollar" style="color:#0f766e;font-size:18px;"></i>
      <div>
        <div style="font-size:15px;font-weight:700;color:#0f172a;">Principal Portal</div>
        <div style="font-size:12px;color:#64748b;">Great Eastern Institute</div>
      </div>
    </div>
    <div style="margin-left:auto;display:flex;align-items:center;gap:12px;">
      <button style="background:none;border:none;cursor:pointer;position:relative;">
        <i class="fa fa-bell" style="font-size:16px;color:#64748b;"></i>
      </button>
      <div style="text-align:right;">
        <div style="font-size:14px;font-weight:600;color:#0f172a;">
          <?= htmlspecialchars(($_SESSION['user']['first_name'] ?? '') . ' ' . ($_SESSION['user']['last_name'] ?? '')) ?>
        </div>
        <div style="font-size:11px;color:#64748b;">School Principal</div>
      </div>
      <div class="header-avatar">
        <?= strtoupper(substr($_SESSION['user']['first_name'] ?? 'P', 0, 1) .
                       substr($_SESSION['user']['last_name']  ?? 'R', 0, 1)) ?>
      </div>
    </div>
  </div>

  <div class="main-content">
  <div class="principal-page">

    <div class="principal-page-header">
      <h1>Payroll Approvals</h1>
      <p>Review and authorize payroll generated by the HR Admin.</p>
    </div>

    <?php if (empty($pending)): ?>
    <!-- ── No Pending ── -->
    <div class="pr-no-pending">
      <i class="fa fa-circle-check"></i>
      <h3>All up to date</h3>
      <p>No payroll periods are currently awaiting your approval.</p>
    </div>

    <?php else: ?>
    <!-- ── Pending Review Cards ── -->
    <?php foreach ($pending as $p):
        $periodLabel = date('M j', strtotime($p['pay_period_start'])) . ' – ' .
                       date('M j, Y', strtotime($p['pay_period_end']));
    ?>
    <div class="pr-pending-card" id="pr-card-<?= $p['period_id'] ?>">
      <div class="pr-pending-header">
        <div>
          <div class="pr-pending-label">Pending Review</div>
          <div class="pr-pending-period">Pay Period: <?= htmlspecialchars($periodLabel) ?></div>
        </div>
        <span class="pr-badge pr-badge--awaiting">Awaiting Approval</span>
      </div>

      <div class="pr-stats-row">
        <div class="pr-stat">
          <div class="pr-stat-label">Total Employees</div>
          <div class="pr-stat-value"><?= (int)$p['emp_count'] ?></div>
        </div>
        <div class="pr-stat">
          <div class="pr-stat-label">Total Gross Payroll</div>
          <div class="pr-stat-value pr-stat-value--lg">₱<?= number_format((float)$p['total_gross'], 2) ?></div>
        </div>
        <div class="pr-stat">
          <div class="pr-stat-label">Total Net Payable</div>
          <div class="pr-stat-value pr-stat-value--lg pr-stat-value--teal">₱<?= number_format((float)$p['total_net'], 2) ?></div>
        </div>
      </div>

      <div class="pr-pending-actions">
        <div class="pr-action-btns">
          <button class="pr-btn-approve"
                  onclick="openApproveConfirm(<?= $p['period_id'] ?>, '<?= htmlspecialchars($periodLabel, ENT_QUOTES) ?>')">
            <i class="fa fa-circle-check"></i> Approve &amp; Authorize Disbursement
          </button>
          <button class="pr-btn-reject"
                  onclick="openRejectModal(<?= $p['period_id'] ?>, '<?= htmlspecialchars($periodLabel, ENT_QUOTES) ?>')">
            <i class="fa fa-circle-xmark"></i> Reject &amp; Return to Admin
          </button>
        </div>
        <div class="pr-view-links">
          <button class="pr-link" onclick="openSummaryModal(<?= $p['period_id'] ?>)">
            <i class="fa fa-eye"></i> View Summary
          </button>
          <button class="pr-link" onclick="openRegisterModal(<?= $p['period_id'] ?>)">
            <i class="fa fa-table-list"></i> Detailed Register
          </button>
          <button class="pr-link" onclick="exportRegisterPDF(<?= $p['period_id'] ?>)">
            <i class="fa fa-download"></i> Download
          </button>
          <a class="pr-link"
             href="<?= BASE_URL ?>modules/payroll/batch-detail.php?period_id=<?= $p['period_id'] ?>"
             style="text-decoration:none;">
            <i class="fa fa-layer-group"></i> Full Details
          </a>
        </div>
      </div>
    </div>
    <?php endforeach; ?>
    <?php endif; ?>

    <!-- ── Past Approved Payrolls ── -->
    <div class="pr-history-section">
      <h2>Past Approved Payrolls</h2>

      <?php if (empty($history)): ?>
      <p style="color:#94a3b8;font-size:14px;padding:20px 0;">No approved payroll history yet.</p>
      <?php else: ?>
      <div class="pr-history-table-wrap">
        <table class="pr-history-table">
          <thead>
            <tr>
              <th>Pay Period</th>
              <th>Approved Date</th>
              <th>Net Payable</th>
              <th>Status</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
          <?php foreach ($history as $h):
              $hl = date('M j', strtotime($h['pay_period_start'])) . ' – ' .
                    date('M j, Y', strtotime($h['pay_period_end']));
              $approvedDate = date('M j, Y', strtotime($h['updated_at']));
          ?>
          <tr>
            <td><strong><?= htmlspecialchars($hl) ?></strong></td>
            <td style="color:#64748b;"><?= $approvedDate ?></td>
            <td><strong>₱<?= number_format((float)$h['total_net'], 2) ?></strong></td>
            <td>
              <span class="pr-badge pr-badge--<?= strtolower($h['status']) ?>">
                <i class="fa fa-lock" style="font-size:10px;"></i>
                <?= ucfirst(strtolower($h['status'])) ?>
              </span>
            </td>
            <td>
              <div style="display:flex;gap:12px;align-items:center;">
                <button class="pr-link" onclick="openSummaryModal(<?= $h['period_id'] ?>)">
                  <i class="fa fa-eye"></i> Summary
                </button>
                <button class="pr-link" onclick="exportRegisterPDF(<?= $h['period_id'] ?>)">
                  <i class="fa fa-download"></i> Export
                </button>
                <a class="pr-link"
                   href="<?= BASE_URL ?>modules/payroll/batch-detail.php?period_id=<?= $h['period_id'] ?>"
                   style="text-decoration:none;">
                  <i class="fa fa-layer-group"></i> Details
                </a>
              </div>
            </td>
          </tr>
          <?php endforeach; ?>
          </tbody>
        </table>
      </div>
      <?php endif; ?>
    </div>

  </div><!-- .principal-page -->
  </div><!-- .main-content -->
</div><!-- .main -->
</div><!-- .layout -->

<!-- ══ MODALS ════════════════════════════════════════════════════════════════ -->
<?php include __DIR__ . '/modals/modal-summary.php'; ?>
<?php include __DIR__ . '/modals/modal-register.php'; ?>
<?php include __DIR__ . '/modals/modal-approve.php'; ?>
<?php include __DIR__ . '/modals/modal-reject.php'; ?>

<!-- ── JS ─────────────────────────────────────────────────────────────────── -->
<script>
const BASE_URL = '<?= BASE_URL ?>';
</script>
<script src="<?= BASE_URL ?>assets/js/principal-payroll-approval.js"></script>

<?php include __DIR__ . '/../../../includes/footer.php'; ?>