<?php
/**
 * modules/principal/payroll-approval/index.php
 * Principal Portal – Payroll Approvals
 */
require_once __DIR__ . '/../../../config/config.php';
require_once __DIR__ . '/../../../includes/auth.php';
requirePrincipal();

// ── Pending periods (PROCESSING — awaiting Principal approval) ────────────────
$pending = $pdo->query("
    SELECT pp.*,
           COUNT(pr.payroll_id)      AS emp_count,
           SUM(pr.gross_pay)         AS total_gross,
           SUM(pr.total_deductions)  AS total_deductions,
           SUM(pr.net_pay)           AS total_net
    FROM payroll_periods pp
    LEFT JOIN payroll_records pr ON pp.period_id = pr.period_id
    WHERE pp.status = 'PROCESSING'
    GROUP BY pp.period_id
    ORDER BY pp.pay_period_start DESC
")->fetchAll();

// ── History (APPROVED / RELEASED) ────────────────────────────────────────────
$history = $pdo->query("
    SELECT pp.*,
           COUNT(pr.payroll_id) AS emp_count,
           SUM(pr.gross_pay)    AS total_gross,
           SUM(pr.net_pay)      AS total_net,
           (SELECT wl2.created_at
            FROM payroll_workflow_log wl2
            WHERE wl2.period_id = pp.period_id AND wl2.event_type = 'APPROVED'
            ORDER BY wl2.created_at DESC LIMIT 1) AS approved_at
    FROM payroll_periods pp
    LEFT JOIN payroll_records pr ON pp.period_id = pr.period_id
    WHERE pp.status IN ('APPROVED','RELEASED')
    GROUP BY pp.period_id
    ORDER BY pp.pay_period_start DESC
")->fetchAll();

// ── Prior rejection context for re-submitted PROCESSING periods ──────────────
$returnHistory  = [];
$submissionMeta = [];
$periodAlerts   = [];
if (!empty($pending)) {
    $pendingIds = implode(',', array_map('intval', array_column($pending, 'period_id')));
    $retRows = $pdo->query("
        SELECT wl.period_id, wl.remarks, wl.created_at, wl.performer_name
        FROM payroll_workflow_log wl
        INNER JOIN (
            SELECT period_id, MAX(created_at) AS latest
            FROM payroll_workflow_log
            WHERE event_type = 'RETURNED' AND period_id IN ($pendingIds)
            GROUP BY period_id
        ) mx ON wl.period_id = mx.period_id AND wl.created_at = mx.latest
        WHERE wl.event_type = 'RETURNED'
    ")->fetchAll();
    foreach ($retRows as $r) $returnHistory[(int)$r['period_id']] = $r;

    $subRows = $pdo->query("
        SELECT period_id, MAX(created_at) AS submitted_at
        FROM payroll_workflow_log
        WHERE event_type = 'SUBMITTED' AND period_id IN ($pendingIds)
        GROUP BY period_id
    ")->fetchAll();
    foreach ($subRows as $r) $submissionMeta[(int)$r['period_id']] = $r['submitted_at'];

    // Alerts: negative net pay or zero basic pay per period
    $alertRows = $pdo->query("
        SELECT period_id,
               SUM(net_pay < 0)   AS neg_net_count,
               SUM(basic_pay = 0) AS zero_basic_count
        FROM payroll_records
        WHERE period_id IN ($pendingIds)
        GROUP BY period_id
    ")->fetchAll();
    foreach ($alertRows as $r) $periodAlerts[(int)$r['period_id']] = $r;
}

$pageTitle = 'Payroll Approvals — Principal Portal';
$extraCSS  = [BASE_URL . 'assets/css/principal.css'];
require_once __DIR__ . '/../../../includes/head.php';
?>
<body>
<div class="layout">
<?php include __DIR__ . '/../../../includes/principal-sidebar.php'; ?>

<div class="main">

<?php include __DIR__ . '/../../../includes/header.php'; ?>

  <div class="main-content">
  <div class="principal-page">

    <div class="principal-page-header">
      <h1>Payroll Approvals</h1>
      <p>Review and authorize payroll generated by the HR Admin.</p>
    </div>

    <?php if (empty($pending)): ?>
    <!-- ── No Pending ── -->
    <div class="pr-no-pending">
      <i class="fa fa-circle-check"></i>
      <h3>All up to date</h3>
      <p>No payroll periods are currently awaiting your approval.</p>
    </div>

    <?php else: ?>
    <!-- ── Pending Review Cards ── -->
    <?php foreach ($pending as $p):
        $periodLabel = date('M j', strtotime($p['pay_period_start'])) . ' – ' .
                       date('M j, Y', strtotime($p['pay_period_end']));
        $pAlerts     = $periodAlerts[(int)$p['period_id']] ?? [];
        $negCount    = (int)($pAlerts['neg_net_count']   ?? 0);
        $zeroCount   = (int)($pAlerts['zero_basic_count'] ?? 0);
    ?>
    <div class="pr-pending-card" id="pr-card-<?= $p['period_id'] ?>">
      <div class="pr-pending-header">
        <div>
          <div class="pr-pending-label">Pending Review</div>
          <div class="pr-pending-period">
            <?= htmlspecialchars($p['period_name'] ?? $periodLabel) ?>
          </div>
          <?php if (!empty($p['payroll_number'])): ?>
          <div style="margin-top:3px;">
            <code style="font-size:11px;color:#64748b;background:#f1f5f9;padding:2px 7px;border-radius:4px;">
              <?= htmlspecialchars($p['payroll_number']) ?>
            </code>
          </div>
          <?php endif; ?>
          <div style="font-size:12px;color:#94a3b8;margin-top:2px;"><?= htmlspecialchars($periodLabel) ?></div>
          <?php if (!empty($submissionMeta[$p['period_id']])): ?>
          <div class="pr-submission-meta">
            <i class="fa fa-paper-plane"></i>
            Submitted <?= date('M j, Y', strtotime($submissionMeta[$p['period_id']])) ?>
          </div>
          <?php endif; ?>
        </div>
        <span class="pr-badge pr-badge--awaiting">Awaiting Approval</span>
      </div>

      <?php if ($negCount > 0 || $zeroCount > 0): ?>
      <div class="pr-alerts-strip">
        <i class="fa fa-triangle-exclamation"></i>
        <strong>Payroll Warnings:</strong>
        <?php if ($negCount > 0): ?>
        <span class="pr-alert-chip pr-alert-chip--red">
          <?= $negCount ?> employee<?= $negCount > 1 ? 's' : '' ?> with negative net pay
        </span>
        <?php endif; ?>
        <?php if ($zeroCount > 0): ?>
        <span class="pr-alert-chip pr-alert-chip--yellow">
          <?= $zeroCount ?> employee<?= $zeroCount > 1 ? 's' : '' ?> with zero basic pay
        </span>
        <?php endif; ?>
      </div>
      <?php endif; ?>

      <div class="pr-stats-row">
        <div class="pr-stat">
          <div class="pr-stat-label">Total Employees</div>
          <div class="pr-stat-value"><?= (int)$p['emp_count'] ?></div>
        </div>
        <div class="pr-stat">
          <div class="pr-stat-label">Total Gross</div>
          <div class="pr-stat-value pr-stat-value--lg">₱<?= number_format((float)$p['total_gross'], 2) ?></div>
        </div>
        <div class="pr-stat">
          <div class="pr-stat-label">Total Deductions</div>
          <div class="pr-stat-value pr-stat-value--lg pr-stat-value--red">₱<?= number_format((float)$p['total_deductions'], 2) ?></div>
        </div>
        <div class="pr-stat">
          <div class="pr-stat-label">Total Net Payable</div>
          <div class="pr-stat-value pr-stat-value--lg pr-stat-value--teal">₱<?= number_format((float)$p['total_net'], 2) ?></div>
        </div>
      </div>

      <?php if (!empty($returnHistory[$p['period_id']])):
          $ret = $returnHistory[$p['period_id']];
      ?>
      <div class="pr-return-notice">
        <div class="pr-return-notice-header">
          <i class="fa fa-rotate-left"></i>
          Previously returned for revision
          <span class="pr-return-notice-date">— <?= date('M j, Y', strtotime($ret['created_at'])) ?></span>
        </div>
        <?php if ($ret['remarks']): ?>
        <div class="pr-return-notice-remarks">"<?= htmlspecialchars($ret['remarks']) ?>"</div>
        <?php endif; ?>
        <div class="pr-return-notice-hint">Admin has revised and resubmitted this payroll for re-review.</div>
      </div>
      <?php endif; ?>

      <div class="pr-pending-actions">
        <div class="pr-action-btns">
          <button class="pr-btn-approve"
                  onclick="openApproveConfirm(<?= $p['period_id'] ?>, '<?= htmlspecialchars($periodLabel, ENT_QUOTES) ?>')">
            <i class="fa fa-circle-check"></i> Approve &amp; Authorize Disbursement
          </button>
          <button class="pr-btn-reject"
                  onclick="openRejectModal(<?= $p['period_id'] ?>, '<?= htmlspecialchars($periodLabel, ENT_QUOTES) ?>')">
            <i class="fa fa-rotate-left"></i> Return for Revision
          </button>
        </div>
        <div class="pr-view-links">
          <button class="pr-link" onclick="openSummaryModal(<?= $p['period_id'] ?>)">
            <i class="fa fa-eye"></i> View Summary
          </button>
          <button class="pr-link" onclick="openRegisterModal(<?= $p['period_id'] ?>)">
            <i class="fa fa-table-list"></i> Detailed Register
          </button>
          <button class="pr-link" onclick="exportRegisterPDF(<?= $p['period_id'] ?>)">
            <i class="fa fa-download"></i> Download
          </button>
          <a class="pr-link"
             href="<?= BASE_URL ?>modules/payroll/batch-detail.php?period_id=<?= $p['period_id'] ?>"
             style="text-decoration:none;">
            <i class="fa fa-layer-group"></i> Full Details
          </a>
        </div>
      </div>
    </div>
    <?php endforeach; ?>
    <?php endif; ?>

    <!-- ── Past Approved Payrolls ── -->
    <div class="pr-history-section">
      <div style="display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:10px;margin-bottom:14px;">
        <h2 style="margin:0;">Past Approved Payrolls</h2>
        <div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap;">
          <input type="text" id="histSearch" placeholder="Search period…"
                 oninput="filterHistory()"
                 style="padding:7px 12px;border-radius:8px;border:1px solid var(--border);font-size:13px;background:#fff;width:200px;">
          <select id="histSort" onchange="sortHistory()"
                  style="padding:7px 12px;border-radius:8px;border:1px solid var(--border);font-size:13px;background:#fff;">
            <option value="date-desc">Newest First</option>
            <option value="date-asc">Oldest First</option>
            <option value="net-desc">Net Pay ↓</option>
            <option value="emp-desc">Employees ↓</option>
          </select>
          <a href="<?= BASE_URL ?>modules/payroll/archive.php"
             style="display:inline-flex;align-items:center;gap:6px;font-size:12px;font-weight:600;color:#7c3aed;text-decoration:none;padding:7px 12px;border-radius:8px;border:1px solid #ddd6fe;background:#f5f3ff;">
            <i class="fa fa-box-archive"></i> Full Archive
          </a>
        </div>
      </div>

      <?php if (empty($history)): ?>
      <p style="color:#94a3b8;font-size:14px;padding:20px 0;">No approved payroll history yet.</p>
      <?php else: ?>
      <div class="pr-history-table-wrap">
        <table class="pr-history-table" id="histTable">
          <thead>
            <tr>
              <th>Payroll #</th>
              <th>Pay Period</th>
              <th style="text-align:center;">Employees</th>
              <th>Net Payable</th>
              <th>Approved Date</th>
              <th>Status</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
          <?php foreach ($history as $h):
              $hl = date('M j', strtotime($h['pay_period_start'])) . ' – ' .
                    date('M j, Y', strtotime($h['pay_period_end']));
              $approvedDate = $h['approved_at']
                  ? date('M j, Y', strtotime($h['approved_at']))
                  : date('M j, Y', strtotime($h['updated_at']));
          ?>
          <tr data-period="<?= strtolower(htmlspecialchars($h['period_name'] ?? $hl)) ?>"
              data-net="<?= (float)$h['total_net'] ?>"
              data-emp="<?= (int)$h['emp_count'] ?>"
              data-date="<?= strtotime($h['pay_period_start']) ?>">
            <td>
              <code style="font-size:11px;color:#64748b;background:#f1f5f9;padding:2px 7px;border-radius:4px;">
                <?= htmlspecialchars($h['payroll_number'] ?? '—') ?>
              </code>
            </td>
            <td>
              <strong><?= htmlspecialchars($h['period_name'] ?? $hl) ?></strong>
              <div style="font-size:11px;color:#94a3b8;margin-top:2px;"><?= htmlspecialchars($hl) ?></div>
            </td>
            <td style="text-align:center;font-weight:600;color:#374151;"><?= (int)$h['emp_count'] ?></td>
            <td><strong>₱<?= number_format((float)$h['total_net'], 2) ?></strong></td>
            <td style="color:#64748b;"><?= $approvedDate ?></td>
            <td>
              <span class="pr-badge pr-badge--<?= strtolower($h['status']) ?>">
                <i class="fa fa-lock" style="font-size:10px;"></i>
                <?= ucfirst(strtolower($h['status'])) ?>
              </span>
            </td>
            <td>
              <div style="display:flex;gap:12px;align-items:center;">
                <button class="pr-link" onclick="openSummaryModal(<?= $h['period_id'] ?>)">
                  <i class="fa fa-eye"></i> Summary
                </button>
                <button class="pr-link" onclick="exportRegisterPDF(<?= $h['period_id'] ?>)">
                  <i class="fa fa-download"></i> Export
                </button>
                <a class="pr-link"
                   href="<?= BASE_URL ?>modules/payroll/batch-detail.php?period_id=<?= $h['period_id'] ?>"
                   style="text-decoration:none;">
                  <i class="fa fa-layer-group"></i> Details
                </a>
              </div>
            </td>
          </tr>
          <?php endforeach; ?>
          </tbody>
        </table>
        <div id="histNoResults" style="display:none;padding:28px;text-align:center;color:#94a3b8;font-size:13px;">
            No periods match your search.
        </div>
      </div>

      <script>
      function filterHistory() {
          const q    = document.getElementById('histSearch').value.toLowerCase().trim();
          const rows = document.querySelectorAll('#histTable tbody tr[data-period]');
          let vis = 0;
          rows.forEach(tr => {
              const show = !q || tr.dataset.period.includes(q);
              tr.style.display = show ? '' : 'none';
              if (show) vis++;
          });
          document.getElementById('histNoResults').style.display =
              (!vis && rows.length > 0) ? 'block' : 'none';
      }

      function sortHistory() {
          const val   = document.getElementById('histSort').value;
          const tbody = document.querySelector('#histTable tbody');
          const rows  = Array.from(tbody.querySelectorAll('tr[data-period]'));
          rows.sort((a, b) => {
              switch (val) {
                  case 'date-asc':  return parseInt(a.dataset.date) - parseInt(b.dataset.date);
                  case 'net-desc':  return parseFloat(b.dataset.net) - parseFloat(a.dataset.net);
                  case 'emp-desc':  return parseInt(b.dataset.emp)  - parseInt(a.dataset.emp);
                  default:          return parseInt(b.dataset.date) - parseInt(a.dataset.date);
              }
          });
          rows.forEach(r => tbody.appendChild(r));
      }
      </script>
      <?php endif; ?>
    </div>

  </div><!-- .principal-page -->
  </div><!-- .main-content -->
</div><!-- .main -->
</div><!-- .layout -->

<!-- ══ MODALS ════════════════════════════════════════════════════════════════ -->
<?php include __DIR__ . '/modals/modal-summary.php'; ?>
<?php include __DIR__ . '/modals/modal-register.php'; ?>
<?php include __DIR__ . '/modals/modal-approve.php'; ?>
<?php include __DIR__ . '/modals/modal-reject.php'; ?>

<!-- ── JS ─────────────────────────────────────────────────────────────────── -->
<script>
const BASE_URL = '<?= BASE_URL ?>';
</script>
<script src="<?= BASE_URL ?>assets/js/principal-payroll-approval.js"></script>

<?php include __DIR__ . '/../../../includes/footer.php'; ?>